version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: monydb
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
    container_name: mony_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      APP_CORS_ALLOWED_ORIGIN: ${SPRING_ALLOWED_ORIGIN}
    ports:
      - "8080:8080"
    restart: always

  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   container_name: mony_frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   restart: always

volumes:
  db_data: {}
